# Generated by Django 5.2.12 on 2026-03-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0002_application_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='contract_file',
            field=models.FileField(blank=True, null=True, upload_to='contracts/'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
