# Generated by Django 5.2.12 on 2026-03-29 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0003_application_contract_file_candidate_resume_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ai_interview_questions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='ai_match_rationale',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='ai_match_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='ai_screening_notes',
            field=models.TextField(blank=True),
        ),
    ]
